### ISSUE TITLE
PHP 8.x Support

### ISSUE THREAD

**Issue by ouun** [ItinerisLtd/wp-phpmailer#508]
Hi @TangRufus,
I use this package for nearly every project, it is so useful and easy to set-up. 
However I am not sure whether you continue to update it. E.g. by adding PHP 8 as requirement in composer.json.
I also added a PR quite a while ago: https://github.com/ItinerisLtd/wp-phpmailer/pull/486

Kind regards,

Philipp

**Comment by TangRufus** [comment]
Glad you find wp-phpmailer helpful. 

However, I left Itineris awhile ago. I am sure @codepuncher would be happy to help.
